// Supabase Database types
// This is a placeholder type since the actual generated types are not available
// The Database type is used as a generic parameter for SupabaseClient

export interface Database {
  public: {
    Tables: {
      // Placeholder for tables - actual types would be generated by Supabase CLI
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
  }
}
